# Generated by Django 6.0.3 on 2026-03-30 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('activation_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activation_logs',
                'ordering': ['-activated_at'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('export', 'Export')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('doctor', 'Doctor'), ('chw', 'Community Health Worker')], default='chw', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('chw_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('doctor_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('home_address', models.TextField(blank=True)),
                ('hospital_name', models.CharField(choices=[('jj_dossen', 'J.J. Dossen Memorial Hospital'), ('other', 'Other')], default='jj_dossen', max_length=100)),
                ('hospital_id', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('specialization', models.CharField(blank=True, choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('ophthalmology', 'Ophthalmology (Eyes)'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('dermatology', 'Dermatology'), ('psychiatry', 'Psychiatry'), ('radiology', 'Radiology'), ('surgery', 'Surgery'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('internal_medicine', 'Internal Medicine'), ('family_medicine', 'Family Medicine'), ('dentistry', 'Dentistry'), ('ent', 'Ear, Nose & Throat (ENT)'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('endocrinology', 'Endocrinology'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology'), ('infectious_disease', 'Infectious Disease'), ('oncology', 'Oncology'), ('hematology', 'Hematology'), ('other', 'Other (Specify)')], max_length=100)),
                ('custom_specialization', models.CharField(blank=True, help_text="Enter custom specialization if 'Other' is selected", max_length=100)),
                ('assigned_village', models.CharField(blank=True, max_length=100)),
                ('activation_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('can_create_patients', models.BooleanField(default=True)),
                ('can_edit_patients', models.BooleanField(default=True)),
                ('can_delete_patients', models.BooleanField(default=False)),
                ('can_create_referrals', models.BooleanField(default=True)),
                ('can_edit_referrals', models.BooleanField(default=True)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
