# Generated by Django 6.0.3 on 2026-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='availability_status',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('on_leave', 'On Leave'), ('off_duty', 'Off Duty')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_response_time',
            field=models.IntegerField(default=0, help_text='Average response time in minutes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='conditions_treated',
            field=models.TextField(blank=True, help_text='Comma-separated list of conditions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consultation_capacity',
            field=models.IntegerField(default=20, help_text='Max patients per day'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='languages_spoken',
            field=models.CharField(blank=True, help_text='e.g., English, Kpelle, Bassa', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Medical license number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_location',
            field=models.CharField(blank=True, help_text='Room number or building', max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='office_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='patient_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='1.00 to 5.00', max_digits=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sub_specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentage of successful treatments', max_digits=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_days',
            field=models.CharField(blank=True, help_text='e.g., Monday,Tuesday,Wednesday', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='working_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
    ]
