# Generated by Django 6.0.3 on 2026-05-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_userprofile_availability_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='conditions_treated',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consultation_fee',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emergency_contact',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='languages_spoken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='office_location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='office_phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sub_specialty',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='working_hours_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='working_hours_start',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avg_response_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='consultation_capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='patient_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
