# Generated by Django 6.0.3 on 2026-04-04 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymptomAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_complaint', models.CharField(max_length=200)),
                ('symptom_duration', models.CharField(help_text='e.g., 2 hours, 3 days', max_length=50)),
                ('severity_score', models.IntegerField(help_text='1-10 scale (10 = worst)')),
                ('associated_symptoms', models.TextField(blank=True, help_text='Comma-separated list')),
                ('symptom_progression', models.CharField(choices=[('worsening', 'Getting Worse'), ('same', 'Staying the Same'), ('improving', 'Getting Better')], default='same', max_length=20)),
                ('consciousness', models.CharField(choices=[('alert', 'Alert and Oriented'), ('confused', 'Confused'), ('unresponsive', 'Unresponsive')], default='alert', max_length=20)),
                ('breathing_status', models.CharField(choices=[('normal', 'Normal'), ('labored', 'Labored'), ('wheezing', 'Wheezing'), ('absent', 'Absent')], default='normal', max_length=20)),
                ('skin_condition', models.CharField(blank=True, max_length=50)),
                ('hydration_status', models.CharField(choices=[('normal', 'Normal'), ('dry_mouth', 'Dry Mouth'), ('sunken_eyes', 'Sunken Eyes')], default='normal', max_length=20)),
                ('current_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('current_bp_systolic', models.IntegerField(blank=True, null=True)),
                ('current_bp_diastolic', models.IntegerField(blank=True, null=True)),
                ('current_pulse', models.IntegerField(blank=True, null=True)),
                ('respiratory_rate', models.IntegerField(blank=True, null=True)),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True)),
                ('ai_urgency', models.CharField(choices=[('emergency', 'Emergency - Immediate Ambulance'), ('urgent', 'Urgent - Within 24 Hours'), ('non_urgent', 'Non-Urgent - Within 1-2 Weeks')], max_length=20)),
                ('ai_specialist', models.CharField(choices=[('cardiology', 'Cardiology (Heart Specialist)'), ('pediatrics', 'Pediatrics (Child Specialist)'), ('ophthalmology', 'Ophthalmology (Eye Specialist)'), ('neurology', 'Neurology (Brain/Nerve Specialist)'), ('gynecology', "Gynecology (Women's Health)"), ('orthopedics', 'Orthopedics (Bone/Joint Specialist)'), ('general_medicine', 'General Medicine'), ('emergency', 'Emergency Department'), ('psychiatry', 'Psychiatry (Mental Health)')], max_length=30)),
                ('ai_confidence', models.IntegerField(help_text='Confidence percentage 0-100')),
                ('ai_recommendation', models.TextField()),
                ('chw_agreed', models.BooleanField(default=False)),
                ('chw_override', models.CharField(blank=True, max_length=20, null=True)),
                ('chw_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_diagnosis', models.CharField(max_length=200)),
                ('actual_specialist', models.CharField(max_length=30)),
                ('actual_urgency', models.CharField(max_length=20)),
                ('ai_was_correct', models.BooleanField(default=False)),
                ('doctor_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_assessment.symptomassessment')),
            ],
        ),
    ]
