# Generated by Django 6.0.3 on 2026-04-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assessment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptomassessment',
            name='ai_recommendation',
        ),
        migrations.AddField(
            model_name='symptomassessment',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text="AI's reasoning for the recommendation"),
        ),
        migrations.AddField(
            model_name='symptomassessment',
            name='recommended_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='symptomassessment',
            name='selected_doctor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='symptomassessment',
            name='warning_signs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptomassessment',
            name='ai_specialist',
            field=models.CharField(choices=[('cardiology', 'Cardiology (Heart)'), ('pediatrics', 'Pediatrics (Children)'), ('ophthalmology', 'Ophthalmology (Eyes)'), ('neurology', 'Neurology (Brain/Nerves)'), ('gynecology', "Gynecology (Women's Health)"), ('orthopedics', 'Orthopedics (Bones/Joints)'), ('general_medicine', 'General Medicine'), ('emergency', 'Emergency Department'), ('psychiatry', 'Psychiatry (Mental Health)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='symptomassessment',
            name='ai_urgency',
            field=models.CharField(choices=[('emergency', 'Emergency - Immediate Action'), ('urgent', 'Urgent - Within 24 Hours'), ('non_urgent', 'Non-Urgent - Within 1-2 Weeks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='symptomassessment',
            name='associated_symptoms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='symptomassessment',
            name='chw_override',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AssessmentFeedback',
        ),
    ]
