# Generated by Django 6.0.3 on 2026-05-07 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_referral_check_in_time_referral_check_out_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referral',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved - Awaiting Doctor'), ('rejected', 'Rejected by Admin'), ('accepted', 'Accepted by Doctor'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_admin', max_length=20),
        ),
        migrations.AlterField(
            model_name='referralactivity',
            name='activity_type',
            field=models.CharField(choices=[('created', 'Referral Created'), ('viewed', 'Referral Viewed'), ('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved by Admin'), ('rejected', 'Rejected by Admin'), ('accepted', 'Accepted by Doctor'), ('started', 'Treatment Started'), ('in_progress', 'Treatment In Progress'), ('completed', 'Treatment Completed'), ('cancelled', 'Referral Cancelled'), ('rejected', 'Referral Rejected'), ('rescheduled', 'Appointment Rescheduled')], max_length=20),
        ),
    ]
