# Generated by Django 6.0.3 on 2026-05-22 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_emergency_phone_and_more'),
        ('referrals', '0004_referral_chw_notification_sent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lost_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(choices=[('no_contact', 'No Contact'), ('moved_away', 'Moved Away'), ('refused_treatment', 'Refused Treatment'), ('transferred', 'Transferred to Another Facility'), ('deceased', 'Deceased'), ('other', 'Other')], max_length=50)),
                ('notes', models.TextField()),
                ('chw_notified', models.BooleanField(default=False)),
                ('doctor_notified', models.BooleanField(default=False)),
                ('recovered', models.BooleanField(default=False)),
                ('recovered_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_records', to='patients.patient')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_record', to='referrals.referral')),
            ],
            options={
                'ordering': ['-lost_date'],
            },
        ),
        migrations.CreateModel(
            name='OverdueFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_type', models.CharField(choices=[('appointment', 'Scheduled Appointment'), ('medication_check', 'Medication Check'), ('test_result', 'Test Result Review'), ('treatment_evaluation', 'Treatment Evaluation')], max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('overdue_days', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('notification_sent', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_followups', to='patients.patient')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overdue_followups', to='referrals.referral')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='PatientCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('missed_appointment', 'Missed Appointment'), ('treatment_update', 'Treatment Update'), ('medication_issue', 'Medication Issue'), ('follow_up_needed', 'Follow-up Needed'), ('emergency_alert', 'Emergency Alert'), ('general', 'General Message')], max_length=50)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('medium', 'Medium Priority'), ('low', 'Low Priority')], default='medium', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('requires_action', models.BooleanField(default=False)),
                ('action_taken', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_communications', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='referrals.referral')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('missed_appointment', 'Missed Appointment'), ('treatment_non_compliance', 'Treatment Non-Compliance'), ('adverse_reaction', 'Adverse Reaction'), ('needs_follow_up', 'Needs Follow-up'), ('referred_back', 'Referred Back to CHW'), ('discharged', 'Discharged')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendations', models.TextField(blank=True)),
                ('action_required', models.BooleanField(default=False)),
                ('acknowledged_by_chw', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_reports', to=settings.AUTH_USER_MODEL)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='referrals.referral')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
