# Generated by Django 6.0.3 on 2026-03-31 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(editable=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('other', 'Other')], default='single', max_length=20)),
                ('village', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('landmark', models.CharField(blank=True, max_length=200, null=True)),
                ('emergency_name', models.CharField(max_length=200)),
                ('emergency_relationship', models.CharField(max_length=100)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('blood_pressure_systolic', models.IntegerField(blank=True, null=True)),
                ('blood_pressure_diastolic', models.IntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('known_conditions', models.TextField(blank=True)),
                ('current_medications', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('past_surgeries', models.TextField(blank=True)),
                ('is_pregnant', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('na', 'Not Applicable')], default='na', max_length=3)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptoms', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment', models.TextField(blank=True)),
                ('referred_to', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
                ('referred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_visits',
                'ordering': ['-visit_date'],
            },
        ),
    ]
