# Generated by Django 6.0.3 on 2026-05-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text="Patient's email address for communication", max_length=254, null=True),
        ),
    ]
